### PR TITLE
shinyapps deploy

### PR DESCRIPTION
**Pull request by brucehoff**
This change will deploy the application to ShinyApps.io.  See README.md for details.

### CODE REVIEW

**Review by j-hendrickson-sage — APPROVED** [review]
Looks viable; I will test in staging

**Comment by j-hendrickson-sage** [comment]
@brucehoff Does the app have any tests?

**Comment by brucehoff** [comment]
> @brucehoff Does the app have any tests?

Not that I have seen, @j-hendrickson-sage .  I would defer to the application creator to explain the lack of tests.

**Comment by avanlinden** [comment]
@j-hendrickson-sage there are no tests for this app currently.

**Review by j-hendrickson-sage — CHANGES_REQUESTED** [review]
@brucehoff From speaking with @avanlinden , this app does not need oauth as there is no sensitive data.  From Abby, "We actually have this app available for anonymous access right now since it's just a dictionary table."  Can we remove the oauth components?

**Comment by brucehoff** [comment]
@j-hendrickson-sage I am closing the PR. Let's hash this out in Slack and revise the PR.

**Pull request closed without merging**
